import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Calendar, RefreshCw, Sparkles, Trash2, ArrowUp, ArrowDown, Check } from "lucide-react";
import StepBar from "@/components/shared/StepBar";
import ToggleSwitch from "@/components/shared/ToggleSwitch";
import Modal from "@/components/shared/Modal";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

const steps = ["Details", "Template", "Recipients", "Schedule"];

interface SeqStep {
  templateName: string;
  day: number;
  sendTime: string;
  timezone: string;
  active: boolean;
}

const CreateSequence = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({
    name: "",
    type: "one-time",
    fromNumber: "",
    retries: false,
    scheduleType: "immediately",
    scheduleDate: "",
    scheduleTime: "",
    fallback: "email",
    recipientType: "contact-list",
  });
  const [seqSteps, setSeqSteps] = useState<SeqStep[]>([]);
  const [recipients, setRecipients] = useState([{ name: "", phone: "" }]);
  const [showAI, setShowAI] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [generating, setGenerating] = useState(false);
  const [contacts, setContacts] = useState<any[]>([]);
  const [selectedContacts, setSelectedContacts] = useState<string[]>([]);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    supabase.from("contacts").select("id, name, phone, created_at").then(({ data }) => {
      if (data) setContacts(data);
    });
  }, []);

  const update = (key: string, val: any) => setForm((p) => ({ ...p, [key]: val }));
  const addStep = () => setSeqSteps((p) => [...p, { templateName: "", day: p.length > 0 ? Math.max(...p.map(s => s.day)) + 2 : 1, sendTime: "09:00", timezone: "IST", active: true }]);
  const removeStep = (i: number) => setSeqSteps((p) => p.filter((_, idx) => idx !== i));
  const moveStep = (i: number, dir: -1 | 1) => {
    const ns = [...seqSteps];
    const j = i + dir;
    if (j < 0 || j >= ns.length) return;
    [ns[i], ns[j]] = [ns[j], ns[i]];
    setSeqSteps(ns);
  };

  const validateStep = (s: number): boolean => {
    const e: Record<string, string> = {};
    if (s === 0 && !form.name.trim()) e.name = "Sequence name is required";
    if (s === 1 && seqSteps.length === 0) e.steps = "Add at least one step";
    if (s === 1 && seqSteps.some(s => !s.templateName.trim())) e.steps = "All steps need a template name";
    if (s === 2 && form.recipientType === "contact-list" && selectedContacts.length === 0) e.recipients = "Select at least one contact";
    if (s === 2 && form.recipientType === "manual" && recipients.every(r => !r.phone.trim())) e.recipients = "Add at least one recipient";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const goNext = () => {
    if (validateStep(step)) setStep(s => Math.min(s + 1, 3));
  };

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-sequence", {
        body: { prompt: aiPrompt },
      });
      if (error) throw error;
      if (data?.steps) setSeqSteps(data.steps);
      setShowAI(false);
      setAiPrompt("");
      toast.success("Sequence generated by AI!");
    } catch {
      toast.error("AI generation failed.");
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = async () => {
    if (!validateStep(3)) return;
    setSubmitting(true);

    const scheduleDate = form.scheduleType === "custom" && form.scheduleDate
      ? new Date(`${form.scheduleDate}T${form.scheduleTime || "09:00"}`).toISOString()
      : null;

    const { data: seq, error } = await supabase.from("sequences").insert({
      user_id: user!.id,
      name: form.name.trim(),
      type: form.type,
      from_number: form.fromNumber,
      retries: form.retries,
      schedule_type: form.scheduleType,
      schedule_date: scheduleDate,
      fallback: form.fallback,
      status: "Draft",
    }).select().single();

    if (error || !seq) { toast.error("Failed to create sequence"); setSubmitting(false); return; }

    if (seqSteps.length > 0) {
      await supabase.from("sequence_steps").insert(
        seqSteps.map((s, i) => ({
          sequence_id: seq.id,
          template_name: s.templateName,
          day: s.day,
          send_time: s.sendTime,
          timezone: s.timezone,
          active: s.active,
          sort_order: i,
        }))
      );
    }

    toast.success("Sequence created!");
    setSubmitting(false);
    navigate("/sequences");
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-semibold text-foreground">Create New Sequence</h1>
          <p className="text-sm text-muted-foreground mt-1">Build an automated WhatsApp messaging sequence</p>
        </div>
        <StepBar steps={steps} current={step} />
      </div>

      <div className="bg-card rounded-xl border border-border p-8 min-h-[420px]">
        {/* Step 0: Details */}
        {step === 0 && (
          <div className="max-w-2xl">
            <h2 className="text-lg font-semibold text-foreground mb-4">Sequence Details</h2>
            <div className="mb-5">
              <label className="text-sm font-medium text-foreground mb-1.5 block">Sequence Name *</label>
              <input className={`border rounded-lg px-4 py-2.5 text-sm w-full bg-background ${errors.name ? "border-destructive" : "border-border"}`} placeholder="e.g., Welcome Drip Campaign" value={form.name} onChange={(e) => { update("name", e.target.value); setErrors({}); }} />
              {errors.name && <p className="text-xs text-destructive mt-1">{errors.name}</p>}
            </div>
            <label className="text-sm font-medium text-foreground mb-3 block">Sequence Type</label>
            <div className="grid grid-cols-2 gap-4 mb-5">
              {[
                { val: "one-time", icon: Calendar, title: "One Time", desc: "Send once to selected recipients" },
                { val: "ongoing", icon: RefreshCw, title: "Ongoing", desc: "Triggered by external events" },
              ].map((opt) => (
                <div key={opt.val} onClick={() => update("type", opt.val)} className={`border-2 rounded-xl p-4 cursor-pointer transition-all ${form.type === opt.val ? "border-crm-blue bg-crm-blue/5" : "border-border hover:border-muted-foreground/30"}`}>
                  <opt.icon size={20} className={`mb-2 ${form.type === opt.val ? "text-crm-blue" : "text-muted-foreground"}`} />
                  <div className="font-semibold text-sm text-foreground">{opt.title}</div>
                  <div className="text-xs text-muted-foreground mt-1">{opt.desc}</div>
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
              <div>
                <label className="text-sm font-medium text-foreground">Activate Retries</label>
                <p className="text-xs text-muted-foreground">Retry failed messages automatically</p>
              </div>
              <ToggleSwitch checked={form.retries} onChange={(v) => update("retries", v)} />
            </div>
            <div className="flex justify-end gap-3 mt-8">
              <button onClick={() => navigate("/sequences")} className="border border-border rounded-lg px-4 py-2 text-sm text-foreground hover:bg-muted">Cancel</button>
              <button onClick={goNext} className="bg-crm-blue text-primary-foreground px-5 py-2 rounded-lg text-sm font-medium hover:bg-crm-blue-dark">Continue</button>
            </div>
          </div>
        )}

        {/* Step 1: Templates */}
        {step === 1 && (
          <div>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-foreground">Message Steps</h2>
              <button onClick={() => setShowAI(true)} className="bg-gradient-to-r from-crm-blue to-indigo-500 text-primary-foreground px-4 py-2 rounded-lg text-sm font-medium hover:opacity-90 inline-flex items-center gap-2">
                <Sparkles size={16} /> Generate with AI
              </button>
            </div>
            {errors.steps && <p className="text-xs text-destructive mb-3">{errors.steps}</p>}
            {seqSteps.length > 0 && (
              <div className="space-y-3 mb-4">
                {seqSteps.map((s, i) => (
                  <div key={i} className="border border-border rounded-xl p-4 bg-background">
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-xs font-semibold text-crm-blue bg-crm-blue/10 px-2 py-0.5 rounded">Step {i + 1}</span>
                      <div className="flex items-center gap-1">
                        <button onClick={() => moveStep(i, -1)} disabled={i === 0} className="p-1 hover:bg-muted rounded disabled:opacity-30"><ArrowUp size={14} /></button>
                        <button onClick={() => moveStep(i, 1)} disabled={i === seqSteps.length - 1} className="p-1 hover:bg-muted rounded disabled:opacity-30"><ArrowDown size={14} /></button>
                        <button onClick={() => removeStep(i)} className="p-1 hover:bg-muted rounded text-destructive"><Trash2 size={14} /></button>
                      </div>
                    </div>
                    <div className="grid grid-cols-4 gap-3">
                      <div className="col-span-2">
                        <label className="text-xs text-muted-foreground mb-1 block">Template Name</label>
                        <input className="border border-border rounded-lg px-3 py-2 text-sm w-full bg-background" placeholder="Template name" value={s.templateName} onChange={(e) => { const ns = [...seqSteps]; ns[i].templateName = e.target.value; setSeqSteps(ns); }} />
                      </div>
                      <div>
                        <label className="text-xs text-muted-foreground mb-1 block">Day</label>
                        <input type="number" min={1} className="border border-border rounded-lg px-3 py-2 text-sm w-full bg-background" value={s.day} onChange={(e) => { const ns = [...seqSteps]; ns[i].day = +e.target.value; setSeqSteps(ns); }} />
                      </div>
                      <div>
                        <label className="text-xs text-muted-foreground mb-1 block">Send Time</label>
                        <input type="time" className="border border-border rounded-lg px-3 py-2 text-sm w-full bg-background" value={s.sendTime} onChange={(e) => { const ns = [...seqSteps]; ns[i].sendTime = e.target.value; setSeqSteps(ns); }} />
                      </div>
                    </div>
                    <div className="flex items-center justify-between mt-3">
                      <span className="text-xs text-muted-foreground">Active</span>
                      <ToggleSwitch checked={s.active} onChange={(v) => { const ns = [...seqSteps]; ns[i].active = v; setSeqSteps(ns); }} />
                    </div>
                  </div>
                ))}
              </div>
            )}
            <button onClick={addStep} className="text-crm-blue text-sm hover:underline border border-dashed border-crm-blue/40 rounded-lg px-4 py-2 w-full text-center">+ Add Step</button>
            <div className="flex justify-end gap-3 mt-8">
              <button onClick={() => setStep(0)} className="border border-border rounded-lg px-4 py-2 text-sm text-foreground hover:bg-muted">Back</button>
              <button onClick={goNext} className="bg-crm-blue text-primary-foreground px-5 py-2 rounded-lg text-sm font-medium hover:bg-crm-blue-dark">Continue</button>
            </div>
          </div>
        )}

        {/* Step 2: Recipients */}
        {step === 2 && (
          <div>
            <h2 className="text-lg font-semibold text-foreground mb-4">Select Recipients</h2>
            {errors.recipients && <p className="text-xs text-destructive mb-3">{errors.recipients}</p>}
            <div className="grid grid-cols-2 gap-4 mb-6">
              {[
                { val: "contact-list", title: "Contact List", desc: "Select from existing contacts" },
                { val: "manual", title: "Manual Entry", desc: "Add recipients manually" },
              ].map((opt) => (
                <div key={opt.val} onClick={() => update("recipientType", opt.val)} className={`border-2 rounded-xl p-4 cursor-pointer transition-all ${form.recipientType === opt.val ? "border-crm-blue bg-crm-blue/5" : "border-border hover:border-muted-foreground/30"}`}>
                  <div className="font-semibold text-sm text-foreground">{opt.title}</div>
                  <div className="text-xs text-muted-foreground mt-1">{opt.desc}</div>
                </div>
              ))}
            </div>
            {form.recipientType === "contact-list" ? (
              <div className="border border-border rounded-xl overflow-hidden">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-muted/50 border-b border-border">
                      <th className="p-3 w-8"><input type="checkbox" checked={selectedContacts.length === contacts.length && contacts.length > 0} onChange={() => setSelectedContacts(selectedContacts.length === contacts.length ? [] : contacts.map(c => c.id))} /></th>
                      <th className="text-left p-3 font-medium text-muted-foreground">Name</th>
                      <th className="text-left p-3 font-medium text-muted-foreground">Phone</th>
                      <th className="text-left p-3 font-medium text-muted-foreground">Added</th>
                    </tr>
                  </thead>
                  <tbody>
                    {contacts.length === 0 ? (
                      <tr><td colSpan={4} className="text-center py-8 text-muted-foreground">No contacts. Add contacts first.</td></tr>
                    ) : contacts.map((c: any) => (
                      <tr key={c.id} className="border-b border-border hover:bg-muted/30">
                        <td className="p-3"><input type="checkbox" checked={selectedContacts.includes(c.id)} onChange={() => setSelectedContacts(prev => prev.includes(c.id) ? prev.filter(x => x !== c.id) : [...prev, c.id])} /></td>
                        <td className="p-3 text-foreground">{c.name}</td>
                        <td className="p-3 text-muted-foreground">{c.phone}</td>
                        <td className="p-3 text-muted-foreground text-xs">{new Date(c.created_at).toLocaleDateString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {selectedContacts.length > 0 && (
                  <div className="px-3 py-2 bg-crm-blue/5 text-xs text-crm-blue font-medium">{selectedContacts.length} contact(s) selected</div>
                )}
              </div>
            ) : (
              <div className="space-y-2">
                {recipients.map((r, i) => (
                  <div key={i} className="flex gap-3">
                    <input className="border border-border rounded-lg px-3 py-2 text-sm flex-1 bg-background" placeholder="Name (optional)" value={r.name} onChange={(e) => { const nr = [...recipients]; nr[i].name = e.target.value; setRecipients(nr); }} />
                    <input className="border border-border rounded-lg px-3 py-2 text-sm flex-1 bg-background" placeholder="WhatsApp Number" value={r.phone} onChange={(e) => { const nr = [...recipients]; nr[i].phone = e.target.value; setRecipients(nr); }} />
                    <button onClick={() => setRecipients(p => p.filter((_, idx) => idx !== i))} className="text-destructive p-2 hover:bg-muted rounded"><Trash2 size={14} /></button>
                  </div>
                ))}
                <button onClick={() => setRecipients(p => [...p, { name: "", phone: "" }])} className="text-crm-blue text-sm hover:underline">+ Add Recipient</button>
              </div>
            )}
            <div className="flex justify-end gap-3 mt-8">
              <button onClick={() => setStep(1)} className="border border-border rounded-lg px-4 py-2 text-sm text-foreground hover:bg-muted">Back</button>
              <button onClick={goNext} className="bg-crm-blue text-primary-foreground px-5 py-2 rounded-lg text-sm font-medium hover:bg-crm-blue-dark">Continue</button>
            </div>
          </div>
        )}

        {/* Step 3: Schedule & Review */}
        {step === 3 && (
          <div>
            <h2 className="text-lg font-semibold text-foreground mb-4">Schedule & Review</h2>
            <div className="grid grid-cols-2 gap-4 mb-6">
              {[
                { val: "immediately", title: "Send Immediately", desc: "Messages go out right away" },
                { val: "custom", title: "Schedule", desc: "Pick a specific date and time" },
              ].map((opt) => (
                <div key={opt.val} onClick={() => update("scheduleType", opt.val)} className={`border-2 rounded-xl p-4 cursor-pointer transition-all ${form.scheduleType === opt.val ? "border-crm-blue bg-crm-blue/5" : "border-border hover:border-muted-foreground/30"}`}>
                  <div className="font-semibold text-sm text-foreground">{opt.title}</div>
                  <div className="text-xs text-muted-foreground mt-1">{opt.desc}</div>
                </div>
              ))}
            </div>
            {form.scheduleType === "custom" && (
              <div className="flex gap-3 mb-5">
                <input type="date" className="border border-border rounded-lg px-4 py-2.5 text-sm bg-background" value={form.scheduleDate} onChange={(e) => update("scheduleDate", e.target.value)} />
                <input type="time" className="border border-border rounded-lg px-4 py-2.5 text-sm bg-background" value={form.scheduleTime} onChange={(e) => update("scheduleTime", e.target.value)} />
              </div>
            )}
            <div className="mb-6">
              <label className="text-sm font-medium text-foreground mb-2 block">Fallback Channel</label>
              <div className="flex gap-3">
                {["email", "whatsapp"].map((ch) => (
                  <label key={ch} className="flex items-center gap-2 text-sm capitalize cursor-pointer">
                    <input type="radio" name="fallback" checked={form.fallback === ch} onChange={() => update("fallback", ch)} className="accent-crm-blue" />
                    {ch}
                  </label>
                ))}
              </div>
            </div>

            {/* Summary */}
            <div className="bg-muted/50 rounded-xl p-5 mb-6">
              <h3 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2"><Check size={16} className="text-crm-green" /> Summary</h3>
              <div className="grid grid-cols-2 gap-y-2 text-sm">
                <span className="text-muted-foreground">Name:</span><span className="text-foreground font-medium">{form.name}</span>
                <span className="text-muted-foreground">Type:</span><span className="text-foreground capitalize">{form.type}</span>
                <span className="text-muted-foreground">Steps:</span><span className="text-foreground">{seqSteps.length} message(s)</span>
                <span className="text-muted-foreground">Recipients:</span><span className="text-foreground">{form.recipientType === "contact-list" ? `${selectedContacts.length} contacts` : `${recipients.filter(r => r.phone).length} manual`}</span>
                <span className="text-muted-foreground">Schedule:</span><span className="text-foreground capitalize">{form.scheduleType === "custom" ? `${form.scheduleDate} ${form.scheduleTime}` : "Immediately"}</span>
                <span className="text-muted-foreground">Fallback:</span><span className="text-foreground capitalize">{form.fallback}</span>
              </div>
            </div>

            <div className="flex justify-end gap-3">
              <button onClick={() => setStep(2)} className="border border-border rounded-lg px-4 py-2 text-sm text-foreground hover:bg-muted">Back</button>
              <button onClick={handleSubmit} disabled={submitting} className="bg-crm-blue text-primary-foreground px-6 py-2 rounded-lg text-sm font-medium hover:bg-crm-blue-dark disabled:opacity-50">
                {submitting ? "Creating..." : "Create Sequence"}
              </button>
            </div>
          </div>
        )}
      </div>

      {showAI && (
        <Modal title="Generate Sequence with AI" onClose={() => setShowAI(false)}>
          <p className="text-sm text-muted-foreground mb-3">Describe your campaign goal and AI will generate message steps.</p>
          <textarea className="border border-border rounded-lg px-4 py-3 text-sm w-full resize-none mb-4 bg-background" rows={4} placeholder="e.g., A 7-day welcome series for new e-commerce customers with product recommendations and discount offers..." value={aiPrompt} onChange={(e) => setAiPrompt(e.target.value)} />
          <div className="flex justify-end">
            <button onClick={handleAIGenerate} disabled={generating || !aiPrompt.trim()} className="bg-gradient-to-r from-crm-blue to-indigo-500 text-primary-foreground px-5 py-2 rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50 inline-flex items-center gap-2">
              <Sparkles size={14} />
              {generating ? "Generating..." : "Generate"}
            </button>
          </div>
        </Modal>
      )}
    </div>
  );
};

export default CreateSequence;
