import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Sparkles, MessageSquare, ShieldCheck, Megaphone, X } from "lucide-react";
import Modal from "@/components/shared/Modal";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

const categories = [
  { value: "Marketing", icon: Megaphone, desc: "Promotions, offers & announcements" },
  { value: "Utility", icon: MessageSquare, desc: "Order updates, reminders & alerts" },
  { value: "Authentication", icon: ShieldCheck, desc: "OTP, verification & security codes" },
];

const NewTemplate = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [name, setName] = useState("");
  const [category, setCategory] = useState("Marketing");
  const [buttonType, setButtonType] = useState("None");
  const [headerType, setHeaderType] = useState("None");
  const [headerText, setHeaderText] = useState("");
  const [body, setBody] = useState("");
  const [footer, setFooter] = useState("");
  const [varCount, setVarCount] = useState(0);
  const [showAI, setShowAI] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validate = () => {
    const e: Record<string, string> = {};
    if (!name.trim()) e.name = "Template name is required";
    if (name.length > 100) e.name = "Name must be under 100 characters";
    if (!body.trim()) e.body = "Template body is required";
    if (body.length > 1024) e.body = "Body must be under 1024 characters";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const addVariable = () => {
    const next = varCount + 1;
    setVarCount(next);
    setBody((p) => p + `{{${next}}}`);
  };

  const handleGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-template", {
        body: { prompt: aiPrompt, category },
      });
      if (error) throw error;
      if (data?.body) setBody(data.body);
      if (data?.header) { setHeaderText(data.header); setHeaderType("Text"); }
      if (data?.footer) setFooter(data.footer);
      setShowAI(false);
      setAiPrompt("");
      toast.success("Template generated by AI!");
    } catch (e: any) {
      toast.error(e?.message || "AI generation failed. Try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!validate()) return;
    setSaving(true);
    const { error } = await supabase.from("templates").insert({
      user_id: user!.id,
      name: name.trim(),
      category,
      body: body.trim(),
      header: headerText || null,
      footer: footer || null,
      button_type: buttonType,
    });
    if (error) {
      toast.error("Failed to save template");
    } else {
      toast.success("Template saved!");
      navigate("/templates");
    }
    setSaving(false);
  };

  const renderPreviewBody = () => {
    return body.replace(/\{\{(\d+)\}\}/g, (_, n) => `[Variable ${n}]`);
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-5">
        <div>
          <h1 className="text-xl font-semibold text-foreground">Create New Template</h1>
          <p className="text-sm text-muted-foreground mt-1">Design a WhatsApp message template for your campaigns</p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => navigate("/templates")} className="border border-border rounded-lg px-4 py-2 text-sm text-foreground hover:bg-muted transition-colors">Cancel</button>
          <button onClick={handleSave} disabled={saving} className="bg-crm-blue text-primary-foreground px-5 py-2 rounded-lg text-sm font-medium hover:bg-crm-blue-dark transition-colors disabled:opacity-50">
            {saving ? "Saving..." : "Save Template"}
          </button>
        </div>
      </div>

      {/* Category Selection */}
      <div className="mb-6">
        <label className="text-sm font-medium text-foreground mb-3 block">Category</label>
        <div className="grid grid-cols-3 gap-3">
          {categories.map((c) => (
            <div key={c.value} onClick={() => setCategory(c.value)} className={`border-2 rounded-xl p-4 cursor-pointer transition-all ${category === c.value ? "border-crm-blue bg-crm-blue/5" : "border-border hover:border-muted-foreground/30"}`}>
              <c.icon size={20} className={`mb-2 ${category === c.value ? "text-crm-blue" : "text-muted-foreground"}`} />
              <div className="font-semibold text-sm text-foreground">{c.value}</div>
              <div className="text-xs text-muted-foreground mt-0.5">{c.desc}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Name & Button Type */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <label className="text-sm font-medium text-foreground mb-1.5 block">Template Name *</label>
          <input className={`border rounded-lg px-4 py-2.5 text-sm w-full bg-background ${errors.name ? "border-destructive" : "border-border"}`} placeholder="e.g., Welcome Message" value={name} onChange={(e) => { setName(e.target.value); setErrors(p => ({...p, name: ""})); }} />
          {errors.name && <p className="text-xs text-destructive mt-1">{errors.name}</p>}
        </div>
        <div>
          <label className="text-sm font-medium text-foreground mb-1.5 block">Button Type</label>
          <select className="border border-border rounded-lg px-4 py-2.5 text-sm w-full bg-background" value={buttonType} onChange={(e) => setButtonType(e.target.value)}>
            <option>None</option><option>Copy Code</option><option>URL</option><option>Quick Reply</option>
          </select>
        </div>
      </div>

      <div className="flex gap-6">
        {/* WhatsApp Preview */}
        <div className="w-[300px] flex-shrink-0">
          <label className="text-sm font-medium text-foreground mb-3 block">Preview</label>
          <div className="bg-[#0b141a] rounded-2xl p-4 relative">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-full bg-crm-blue/20 flex items-center justify-center">
                <MessageSquare size={14} className="text-crm-blue" />
              </div>
              <div>
                <div className="text-xs font-medium text-white/90">WhatsApp Preview</div>
                <div className="text-[10px] text-white/50">How your message will look</div>
              </div>
            </div>
            <div className="bg-[#005c4b] rounded-lg p-3 text-sm relative ml-4">
              <div className="absolute -left-2 top-0 w-0 h-0 border-t-[8px] border-t-[#005c4b] border-l-[8px] border-l-transparent" />
              {headerText && <div className="font-bold text-white mb-1.5 text-[13px]">{headerText}</div>}
              <div className="text-white/90 whitespace-pre-wrap text-xs leading-relaxed">
                {body ? renderPreviewBody() : "Your message preview will appear here..."}
              </div>
              {footer && <div className="text-white/50 text-[10px] mt-2">{footer}</div>}
              {buttonType !== "None" && (
                <div className="mt-2 pt-2 border-t border-white/10">
                  <div className="text-[#53bdeb] text-xs text-center font-medium">{buttonType}</div>
                </div>
              )}
              <div className="text-right mt-1">
                <span className="text-[10px] text-white/40">12:00 PM ✓✓</span>
              </div>
            </div>
          </div>
        </div>

        {/* Form */}
        <div className="flex-1 space-y-5">
          <div>
            <label className="text-sm font-medium text-foreground">Header (Optional)</label>
            <p className="text-xs text-muted-foreground mb-2">Add a title or select media type</p>
            <div className="flex items-center gap-4 mb-2">
              {["None", "Text", "Image", "Video", "Document"].map((t) => (
                <label key={t} className="flex items-center gap-1.5 text-sm cursor-pointer">
                  <input type="radio" name="headerType" checked={headerType === t} onChange={() => setHeaderType(t)} className="accent-crm-blue" />
                  {t}
                </label>
              ))}
            </div>
            {headerType === "Text" && <input className="border border-border rounded-lg px-4 py-2.5 text-sm w-full bg-background" placeholder="Header text" maxLength={60} value={headerText} onChange={(e) => setHeaderText(e.target.value)} />}
          </div>

          <button onClick={() => setShowAI(true)} className="bg-gradient-to-r from-crm-blue to-indigo-500 text-primary-foreground px-5 py-2.5 rounded-lg text-sm font-medium hover:opacity-90 transition-opacity inline-flex items-center gap-2 shadow-sm">
            <Sparkles size={16} /> Generate with AI
          </button>

          <div>
            <label className="text-sm font-medium text-foreground">Body *</label>
            <p className="text-xs text-muted-foreground mb-2">The WhatsApp message content with optional variables</p>
            <textarea className={`border rounded-lg px-4 py-3 text-sm w-full resize-none bg-background ${errors.body ? "border-destructive" : "border-border"}`} rows={6} placeholder="Type your message here..." maxLength={1024} value={body} onChange={(e) => { setBody(e.target.value); setErrors(p => ({...p, body: ""})); }} />
            {errors.body && <p className="text-xs text-destructive mt-1">{errors.body}</p>}
            <div className="flex items-center justify-between mt-1">
              <div className="flex items-center gap-2">
                <button onClick={addVariable} className="text-crm-blue text-xs hover:underline border border-crm-blue/30 rounded-full px-3 py-1">+ Add Variable</button>
                {varCount > 0 && <span className="text-xs text-muted-foreground">{varCount} variable(s) used</span>}
              </div>
              <span className={`text-xs ${body.length > 900 ? "text-destructive" : "text-muted-foreground"}`}>{body.length}/1024</span>
            </div>
          </div>

          <div>
            <label className="text-sm font-medium text-foreground">Footer (Optional)</label>
            <p className="text-xs text-muted-foreground mb-2">Add a short line of text to the bottom of your template.</p>
            <input className="border border-border rounded-lg px-4 py-2.5 text-sm w-full bg-background" placeholder="e.g., Powered by LeadBug" maxLength={60} value={footer} onChange={(e) => setFooter(e.target.value)} />
          </div>
        </div>
      </div>

      {showAI && (
        <Modal title="Generate Template with AI" onClose={() => setShowAI(false)}>
          <p className="text-sm text-muted-foreground mb-3">Describe the purpose and tone of your WhatsApp template, and AI will generate professional content.</p>
          <textarea className="border border-border rounded-lg px-4 py-3 text-sm w-full resize-none mb-3 bg-background focus:ring-2 focus:ring-crm-blue/20 focus:border-crm-blue transition-all" rows={4} placeholder="e.g., A welcome message for new customers who just signed up, with a 10% discount offer..." value={aiPrompt} onChange={(e) => setAiPrompt(e.target.value)} />
          <div className="flex items-center justify-between">
            <span className="text-xs text-muted-foreground">Category: {category}</span>
            <button onClick={handleGenerate} disabled={generating || !aiPrompt.trim()} className="bg-gradient-to-r from-crm-blue to-indigo-500 text-primary-foreground px-5 py-2 rounded-lg text-sm font-medium hover:opacity-90 transition-opacity disabled:opacity-50 inline-flex items-center gap-2">
              <Sparkles size={14} />
              {generating ? "Generating..." : "Generate Template"}
            </button>
          </div>
        </Modal>
      )}
    </div>
  );
};

export default NewTemplate;
